# Generated by Django 4.2.7 on 2024-02-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="authuser",
            name="membership_plan",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "BASIC_PLAN"), (2, "PREMIUM_PLAN"), (3, "VIP_PLAN")],
                db_index=True,
                default=1,
                help_text="Membership plan",
                null=True,
            ),
        ),
    ]
