# Generated by Django 4.2.7 on 2024-03-02 01:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "Ciudad", "verbose_name_plural": "Ciudades"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "País", "verbose_name_plural": "Paises"},
        ),
        migrations.AlterModelOptions(
            name="userzone",
            options={
                "verbose_name": "Barrio del usuario",
                "verbose_name_plural": "Barrios de los usuarios",
            },
        ),
        migrations.AlterModelOptions(
            name="zone",
            options={"verbose_name": "Barrio", "verbose_name_plural": "Barrios"},
        ),
    ]
