# Generated by Django 4.2.7 on 2023-12-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_city_country_remove_authuser_office_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authuser",
            name="office_location_tags",
        ),
        migrations.AddField(
            model_name="authuser",
            name="office_locations",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="auth_user_set", to="core.zone"
            ),
        ),
    ]
