HOMBRE = 1
MUJER = 2

GENDER_CHOICES = (
    (HOMBRE, "HOMBRE"),
    (MUJER, "MUJER"),
)

# model: UserAttachment
USER_IMAGE = 1
USER_ATTACHMENT = 2

SOURCE_CONTENT_TYPE_CHOICES = (
    (USER_IMAGE, "USER_IMAGE"),
    (USER_ATTACHMENT, "USER_ATTACHMENT"),
)
