# Generated by Django 4.2.7 on 2024-02-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("psychology", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercarreer",
            name="service_method",
            field=models.SmallIntegerField(
                choices=[(1, "PRESENCIAL"), (2, "VIRTUAL"), (3, "DOMICILIO")], default=2
            ),
        ),
        migrations.AlterField(
            model_name="usercarreer",
            name="service_modality",
            field=models.SmallIntegerField(
                choices=[(1, "INDIVIDUAL"), (2, "GRUPAL")], default=1
            ),
        ),
    ]
