# Generated by Django 4.2.7 on 2024-02-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("psychology", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userattachment",
            name="source_content_type",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "USER_IMAGE"), (2, "USER_DNI"), (3, "USER_MATRICULA")],
                db_index=True,
                null=True,
            ),
        ),
    ]
