# Generated by Django 4.2.7 on 2023-11-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("psychology", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpayment",
            name="concept",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "PAYMENT_MONTH"),
                    (2, "PAYMENT_FORMATION"),
                    (3, "PAYMENT_SUPERVITION"),
                    (4, "PAYMENT_VIRTUAL"),
                    (5, "PAYMENT_VIP"),
                ],
                db_index=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userpayment",
            name="was_paid",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
