# Generated by Django 4.2.7 on 2024-03-02 01:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("psychology", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminemailnotification",
            options={
                "verbose_name": "Notificación de Email",
                "verbose_name_plural": "Notificaciones de Email",
            },
        ),
        migrations.AlterModelOptions(
            name="carreer",
            options={"verbose_name": "Carrera", "verbose_name_plural": "Carreras"},
        ),
        migrations.AlterModelOptions(
            name="contactme",
            options={
                "verbose_name": "Derivaciôn",
                "verbose_name_plural": "Derivaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="language",
            options={"verbose_name": "Idioma", "verbose_name_plural": "Idiomas"},
        ),
        migrations.AlterModelOptions(
            name="membership",
            options={"verbose_name": "Plan", "verbose_name_plural": "Planes"},
        ),
        migrations.AlterModelOptions(
            name="membershipprice",
            options={
                "verbose_name": "Precio del plan",
                "verbose_name_plural": "Precios por planes",
            },
        ),
        migrations.AlterModelOptions(
            name="specialization",
            options={
                "verbose_name": "Especialización",
                "verbose_name_plural": "Especializaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="userattachment",
            options={
                "verbose_name": "Archivo del usuario",
                "verbose_name_plural": "Archivos de los usuarios",
            },
        ),
        migrations.AlterModelOptions(
            name="usercarreer",
            options={
                "verbose_name": "Profesión del usuario",
                "verbose_name_plural": "Profesión de los usuarios",
            },
        ),
        migrations.AlterModelOptions(
            name="userlanguage",
            options={
                "verbose_name": "Idioma de usuario",
                "verbose_name_plural": "Idiomas de los usuarios",
            },
        ),
        migrations.AlterModelOptions(
            name="userpayment",
            options={
                "verbose_name": "Pago del usuario",
                "verbose_name_plural": "Pagos de los usuarios",
            },
        ),
        migrations.AlterModelOptions(
            name="userspecialization",
            options={
                "verbose_name": "Especialización del usuario ",
                "verbose_name_plural": "Especializaciones de los usuarios",
            },
        ),
    ]
