# Generated by Django 4.2.7 on 2023-12-13 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("psychology", "0003_specialization_alter_userpayment_concept_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carreer",
            name="specialization",
        ),
        migrations.AddField(
            model_name="usercarreer",
            name="specialization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_carreer_set",
                to="psychology.specialization",
            ),
        ),
    ]
