# Generated by Django 4.2.7 on 2023-12-13 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("psychology", "0004_remove_carreer_specialization_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercarreeraudience",
            name="audience",
        ),
        migrations.RemoveField(
            model_name="usercarreeraudience",
            name="user_carreer",
        ),
        migrations.RemoveField(
            model_name="usercarreer",
            name="audiences",
        ),
        migrations.DeleteModel(
            name="Audience",
        ),
        migrations.DeleteModel(
            name="UserCarreerAudience",
        ),
    ]
