# Generated by Django 4.2.7 on 2023-12-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("psychology", "0005_remove_usercarreeraudience_audience_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercarreer",
            name="specialization",
        ),
        migrations.AddField(
            model_name="usercarreer",
            name="specialization",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="user_carreer_set",
                to="psychology.specialization",
            ),
        ),
    ]
