# Generated by Django 4.2.7 on 2023-12-13 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("psychology", "0006_remove_usercarreer_specialization_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usercarreer",
            old_name="specialization",
            new_name="specializations",
        ),
    ]
