# Generated by Django 4.2.7 on 2023-12-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("psychology", "0007_rename_specialization_usercarreer_specializations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercarreer",
            name="specializations",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_carreer_set",
                to="psychology.specialization",
            ),
        ),
    ]
